# Generated by Django 5.0.14 on 2025-07-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_equipo_usuario_impresora_usuario_movil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='impresora',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='movil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_ad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_office',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_sap',
        ),
        migrations.CreateModel(
            name='UsuarioAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_ad', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_office', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('impresora', models.CharField(blank=True, max_length=100, null=True)),
                ('movil', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_ad', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'Usuarios_Ad',
            },
        ),
    ]
