# Generated by Django 5.0.14 on 2025-07-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_equipo_remove_usuario_impresora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id_conversion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_conversion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Conversion',
            },
        ),
        migrations.CreateModel(
            name='ConvKilos',
            fields=[
                ('id_convkilos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_convkilos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ConvKilos',
            },
        ),
        migrations.CreateModel(
            name='DescripcionCatalogo',
            fields=[
                ('id_descripcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DescripcionCatalogo',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='NProveedor',
            fields=[
                ('id_nproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('n_proveedor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NProveedor',
            },
        ),
        migrations.CreateModel(
            name='OrigenCotizacion',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False)),
                ('origen_cotizacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'OrigenCotizacion',
            },
        ),
        migrations.CreateModel(
            name='RutProveedor',
            fields=[
                ('id_rut', models.AutoField(primary_key=True, serialize=False)),
                ('rut_proveedor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'RutProveedor',
            },
        ),
        migrations.CreateModel(
            name='SinSKU',
            fields=[
                ('id_sinsku', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sinsku', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SinSKU',
            },
        ),
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id_tipo_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_solicitud', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'TipoSolicitud',
            },
        ),
        migrations.CreateModel(
            name='UDM',
            fields=[
                ('id_udm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_udm', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UDM',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCodigos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('cotizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('n_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_fab_modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
                ('origen', models.ForeignKey(db_column='origen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.origencotizacion')),
                ('rut', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='usuarios.rutproveedor')),
                ('tipo_solicitud', models.ForeignKey(db_column='tipo_solicitud', on_delete=django.db.models.deletion.CASCADE, to='usuarios.tiposolicitud')),
                ('udm', models.ForeignKey(db_column='udm', on_delete=django.db.models.deletion.CASCADE, to='usuarios.udm')),
            ],
            options={
                'db_table': 'SolicitudCodigos',
            },
        ),
    ]
